import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";
import MuiThemeProvider from "./utils/Providers/ThemeProvider";
import Footer from "./Components/Footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <MuiThemeProvider>
          <Header />
          {children}
          <Footer />
        </MuiThemeProvider>
      </body>
    </html>
  );
}
